// A triangle number is generated by adding natural numbers in a row.
// Example:
// 0 + 1 = 1
// 0 + 1 + 2 = 3
// 0 + 1 + 2 + 3 = 6
// 0 + 1 + 2 + 3 + 4 = 10

// As displayed above, the first 4 triangle numbers are 1, 3, 6, and 10.
// If we display the factor of each triangle number...
//  1: 1
//  3: 1, 3
//  6: 1, 2, 3, 6
//  10: 1, 2, 5, 10

//  The triangle number "10" has 4 divisors.
//  What is the first triangle number to have over 500 divisors?

#include <limits.h>
#include <stdio.h>

int main(void) {

    // variables for triangle number and total divisors
    int tr = 1;
    int divisors = 0;

    // generate triangle numbers
    for (int i = 1; i < INT_MAX; i++) {
        tr += (i + 1);

        // check divisor count
        for (int d = 1; d <= tr; d++) {
            if (tr % d == 0) {
                divisors++;
            }
        }
        if (divisors > 500) {
            printf("%d\n", tr);
            return 0;
        }
        
        // reset divisors
        divisors = 0;
    }

    return 0;
}
